### ISSUE TITLE
Teamcity build failure after upgrading from 3.0.3 to 4.1.0

### ISSUE THREAD

**Issue by TraGicCode** [cake-contrib/Cake.BuildSystems.Module#116]
We updated our cake build script to use 4.1.0 instead of 3.0.3 and now our build is bombing out with an error but it's only happening when the teamcity agent kicks of the build.  Connecting to the same machine and running the same commandline as the teamcity agent causes the build to work perfectly fine.  We tried restarting the teamcity build agent along with doing a git clean -dfx and we have had no luck.  We could use some help on this.  Below is the error we see from our teamcity agent logs for the failed build

TeamCity Agent Build Logs
![image](https://user-images.githubusercontent.com/6224270/149194956-2269261f-439d-41c9-8293-84249951758d.png)

Cake Build Script

I have only pasted the module pragma.

```
// modules
#module nuget:?package=Cake.BuildSystems.Module&version=4.1.0
```

**Comment by nils-a** [comment]
@TraGicCode Sorry to hear you are having problems.

The first line in the log you posted shows you are using Cake in version 1.1.0.

Starting from [version 4.0.0](https://github.com/cake-contrib/Cake.BuildSystems.Module/releases/tag/4.0.0), Cake.Buildsystems.Module requires [Cake 2.0.0](https://github.com/cake-build/cake/releases/tag/v2.0.0).

Do you have the same error when running with Cake 2.0.0 ?

**Comment by TraGicCode** [comment]
Hey @nils-a ,

Thanks for the fast reply.  You are indeed correct.  Upgrading to 2.0.0 resolved my issue.

Thank you!
