### ISSUE TITLE
Start supporting Cake 3.0.0

### ISSUE THREAD

**Issue by bdukes** [cake-contrib/Cake.BuildSystems.Module#135]
We [upgraded](https://github.com/dnnsoftware/Dnn.Platform/pull/5442/files) Cake.BuildSystems.Module to 4.2.0, Cake.Frosting to 3.0.0 and Cake.Issues to 2.0.0, and are now getting a [build error](https://dev.azure.com/dotnet/DNN/_build/results?buildId=84375&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d1e88c09-dceb-53c1-5579-19c846f3526a&l=44):

>`Unhandled exception. System.TypeLoadException: Method 'WriteLifeCycleStep' in type 'Cake.AzurePipelines.Module.AzurePipelinesReportPrinter' from assembly 'Cake.AzurePipelines.Module, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`
>`   at Cake.AzurePipelines.Module.AzurePipelinesModule.Register(ICakeContainerRegistrar registrar)`
>`   at Cake.Frosting.ServiceCollectionExtensions.UseModule[TModule](IServiceCollection services)`
>```   at Cake.Frosting.CakeHostExtensions.<>c__8`1.<UseModule>b__8_0(IServiceCollection services)```
>```   at Cake.Frosting.CakeHost.ConfigureServices(Action`1 services)```
>`   at Cake.Frosting.CakeHostExtensions.UseModule[TModule](CakeHost host)`
>`   at DotNetNuke.Build.Program.Main(String[] args) in D:\a\1\s\build\Program.cs:line 26`

No particular rush on the upgrade, just wanted to make sure you were aware and/or we didn't miss anything we needed to do with the upgrade. Thanks!

**Comment by nils-a** [comment]
@bdukes we're currently lagging a bit behind. Cake.BuildSystems.Module in version 4.2 currently does not support Cake 3.0.0
