### ISSUE TITLE
Suport Azure DevOps Server & cake 0.38

### ISSUE THREAD

**Issue by serGrey** [cake-contrib/Cake.BuildSystems.Module#23]
Could you please clarify, is it support Azure DevOps Server & cake 0.38?
I installed Cake.BuildSystems.Module 0.3.2 version, but any changes on the build definition result

**Comment by nils-a** [comment]
@serGrey I did a quick test in Azure DevOps (no "Server" version, though) using Cake 0.38.5 and had no problems.

* in the logs it shows:
  * ![image](https://user-images.githubusercontent.com/349188/98172688-14834c00-1ef2-11eb-8ee4-b84f483ce146.png)
* in the UI it looks like this:
  * ![image](https://user-images.githubusercontent.com/349188/98172560-df76f980-1ef1-11eb-9b52-87f59b66c3bc.png)
  * ![image](https://user-images.githubusercontent.com/349188/98172591-ea318e80-1ef1-11eb-84f4-d5f67742797d.png)

So. Generally using Cake.BuildSystems.Module with Cake 0.38.x and DevOps Server should work.

However, "Activation" for the module in DevOps is tied to the `TF_BUILD` environment-variable. It *should*, according to [the docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables-devops-services) be available in Azure DevOps Server 2019 and 2020 but I can not test that currently.

Also: Is it possible you did not bootstrap the module? I.e. when using the bootstrapper, run `.\build.ps1 --bootstrap` first, before running the build. There will be no error/warning if you do not bootstrap but the module will simply not be used.
