### ISSUE TITLE
Should this work with Cake 1.0.0 (RC1) yet?

### ISSUE THREAD

**Issue by bdukes** [cake-contrib/Cake.BuildSystems.Module#24]
I've added this module to our build at https://github.com/dnnsoftware/Dnn.Platform/pull/4439, but didn't see any changes in the [build output](https://dev.azure.com/dotnet/DNN/_build/results?buildId=44652&view=results).  I'm assuming it's because of the Cake version we're using, or I could just be missing what I should be seeing.  Is there a way to verify whether the tool is being applied?

**Comment by nils-a** [comment]
Sorry to say, it is currently not supposed to work with Cake 1.x, as modules are for the most part bound to the version they were compiled against.

You can add `--verbosity=diagnostic` to the run, to see detailed information including loaded modules.

For a run using Cake 0.34.x it looks like:
![image](https://user-images.githubusercontent.com/349188/106011040-62a38800-60ba-11eb-8a2e-2ab4487ee5ec.png)

For a run using Cake 1.0.0-rc0002 it looks like:
![image](https://user-images.githubusercontent.com/349188/106011156-79e27580-60ba-11eb-860d-1ae45d24207b.png)
