### ISSUE TITLE
CakeModules should be public classes

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.BuildSystems.Module#36]
`MyGetModule`, `TeamCityModule` and `TravisCIModule` are all declared `private class`.
While this works when using `Cake.exe` and `Cake.Tool`, it does not work when using `Cake.Frosting`.

**Comment by nils-a** [comment]
@AdmiringWorm, interested in writing a `Cake.Module.Analyzer`, that checks for this? 😉

**Comment by AdmiringWorm** [comment]
@nils-a not a bad idea, not completely sure if it would be worthwhile creating an analyzer with just 1 rule though. But, I will about it.

**Comment by nils-a** [comment]
@AdmiringWorm If you "need" another rule, you could always require the correct assembly attribute for the module 😉

**Comment by AdmiringWorm** [comment]
@nils-a well, not sure how I would correctly identify that right now.
But I will keep it in mind.
I need to finish up some other things before I even start looking at creating a new analyzer, but hopefully will be able to start working on 1 soon.
