### ISSUE TITLE
Use cake-contrib icon

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.BuildSystems.Module#47]
The [currently used icon](https://github.com/cake-contrib/Cake.BuildSystems.Module/blob/6fbba30a8c2881bda9e9abe9760751be45a083c1/src/Cake.BuildSystems.Module/Cake.BuildSystems.Module.csproj#L29) no longer exists. Module should use cake-contrib icon as in §3.2 in [guidelines](https://cakebuild.net/docs/extending/addins/best-practices#package-metadata).

**Comment by nils-a** [comment]
An Icon according to the guidelines is part of #29 and hence is to added in [#38](https://github.com/cake-contrib/Cake.BuildSystems.Module/pull/38/files#diff-b82c6655e8f627c62c0629228fb0d70ca62cbcad83ab3e7299908d98cd2f03e9R24) .
However, I left the non-functioning URL in. I'll update the PR to use a working URL if that's ok with you, @pascalberger .
