### ISSUE TITLE
Don't include Cake.Core and Cake.Common in NuGet package

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.BuildSystems.Module#51]
The NuGet package for version 2.0 contains `Cake.Core`, `Cake.Common` and `JetBrains.Annotations.dll` in `lib\net461`  folder. They should not be part of the NuGet package, as they are not required.

**Comment by nils-a** [comment]
fixed in https://github.com/cake-contrib/Cake.BuildSystems.Module/commit/5610b50fcb5d6fe24b1dc30ae413408032b8edb1
